### ISSUE TITLE
The application running from is not server side rendered

### ISSUE THREAD

**Issue by zipme** [gangsthub/nuxt-edge-test#2]
The 'application running from' part is not server-side rendered

**Comment by paulmelero** [comment]
You're right, my friend. In Cloudflare's example, I'm not printing that information on the server-side. Thanks for spotting that. I'll take a look at it soon enough to fix it.

Vercel's one is rendered on the server (except for the globe animation): https://nuxt-edge-globe.vercel.app/

**Comment by zipme** [comment]
@gangsthub oh nice, didn't see the vercel example, it does render on server side, nice work!

**Comment by paulmelero** [comment]
Fixed it in https://github.com/gangsthub/nuxt-edge-test/commit/7ddeb168142ba120e140d5e2aa7c28d22b729c06. Now, in

https://nuxt-edge-test.graficos-net.workers.dev/

the "message" (and the **city**) is server-side rendered, as it is in

https://nuxt-edge-globe.vercel.app/

But, what I don't really like is that it seems like `$fetch` is being run both in the client and in the server. There must be an option to avoid that, but I haven't seen it in the docs yet. Might explore more in the future 😉.

Thanks for reporting. Closing this one for now!

**Comment by zipme** [comment]
> Fixed it in [7ddeb16](https://github.com/gangsthub/nuxt-edge-test/commit/7ddeb168142ba120e140d5e2aa7c28d22b729c06). Now, in
> 
> https://nuxt-edge-test.graficos-net.workers.dev/
> 
> the "message" (and the **city**) is server-side rendered, as it is in
> 
> https://nuxt-edge-globe.vercel.app/
> 
> But, what I don't really like is that it seems like `$fetch` is being run both in the client and in the server. There must be an option to avoid that, but I haven't seen it in the docs yet. Might explore more in the future 😉.
> 
> Thanks for reporting. Closing this one for now!

I think it's because you use the raw `$fetch` (from ohmyfetch) instead of `useFetch` which internally uses `useAsyncData` that avoids another call in the client.

Wrapping things in a `useAsyncData` in your `useLocation` function should help.

**Comment by paulmelero** [comment]
Thank you! I'll take a look at it soon enough. Opening a new issue!
